engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/Alias:
        enabled: false
      Rubocop/Style/Documentation:
        enabled: false
      Rubocop/Style/MultilineOperationIndentation:
        enabled: false
ratings:
  paths:
  - "**.rb"
exclude_paths:
- config/**/*
- db/**/*
- test/**/*
- bin/**/*
