# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74bb19f04766904db7c6f2d8ba34ac53cf37da960af9972be29b87cd2076ed87cda9603df9c870d6e6f2dbeb4287916163be37921538931bdfe3888ed5c2efae

test:
  secret_key_base: 06191de2b405b6457e53869d74b5160747f09b914b7229fc857f700dcfcefdabb5932b52e84d3bb98daa282a1b9693258e95ec7b119de51066887a4f803ac003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
